server:
  port: 8080


spring:
  application:
    name: murtada
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: murtada
    password: password
  jpa:
      properties:
       hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      hibernate:
        ddl-auto: update
      show_sql: true
